server.port=${PORT:8080}
server.address=0.0.0.0

spring.data.mongodb.uri=mongodb+srv://mateo:Mateo123@terminsystem.0wf2ewe.mongodb.net/?appName=terminsystem
spring.data.mongodb.database=terminsystem

